### ISSUE TITLE
mac版本报错

### ISSUE THREAD

**Issue by xia0le** [A-D-Team/grafanaExp#3]
![QQ_1720752027583](https://github.com/user-attachments/assets/2b149231-fc61-44c9-ba8a-f010075792dc)

```2024/07/12 10:40:22 Target vulnerable has plugin [alertlist]
2024/07/12 10:40:22 Got secret_key [SW2YcwTIb9zpOOhoPsMm]
panic: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

goroutine 1 [running]:
grafanaExp/internal.getAllDatasource()
        /Users/anyone/Code/golangCode/grafanaExp/internal/exp.go:93 +0xb98
grafanaExp/internal.CheckTargetFunc(0x1013694c0?)
        /Users/anyone/Code/golangCode/grafanaExp/internal/cliFlag.go:124 +0x130
github.com/urfave/cli/v2.(*Command).Run(0x1013694c0, 0x140000b06c0, {0x1400009b410, 0x3, 0x3})
        /Users/anyone/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x780
github.com/urfave/cli/v2.(*Command).Run(0x14000170160, 0x140000b0600, {0x140000b0040, 0x4, 0x4})
        /Users/anyone/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:272 +0x9a0
github.com/urfave/cli/v2.(*App).RunContext(0x1400016e000, {0x101136cb8?, 0x1400009c010}, {0x140000b0040, 0x4, 0x4})
        /Users/anyone/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x61c
github.com/urfave/cli/v2.(*App).Run(...)
        /Users/anyone/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:311
main.main()
        /Users/anyone/Code/golangCode/grafanaExp/cmd/grafanaExp.go:38 +0x1e0

**Comment by purpleroc** [comment]
arm版本还是？amd？

**Comment by xia0le** [comment]
> arm版本还是？amd？
arm的

**Comment by purpleroc** [comment]
试一下最新的这个，我这没环境。换了个 sqlite 包，还没测试。。。

**Comment by purpleroc** [comment]
https://github.com/A-D-Team/grafanaExp/commit/407ba963cb2ee101d42b31f55545627c02a95f54

https://github.com/A-D-Team/grafanaExp/releases/tag/v1.3

**Comment by xia0le** [comment]
> [407ba96](https://github.com/A-D-Team/grafanaExp/commit/407ba963cb2ee101d42b31f55545627c02a95f54)
> 
> https://github.com/A-D-Team/grafanaExp/releases/tag/v1.3
还是报错
```$ ./darwin_arm64_grafanaExp exp -u http://10.211.55.2:3000/
2024/07/12 20:58:37 Target vulnerable has plugin [alertlist]
2024/07/12 20:58:37 Got secret_key [SW2YcwTIb9zpOOhoPsMm]
panic: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

goroutine 1 [running]:
grafanaExp/internal.getAllDatasource()
	/private/tmp/grafanaExp/internal/exp.go:93 +0xab4
grafanaExp/internal.CheckTargetFunc(0x1400018d680?)
	/private/tmp/grafanaExp/internal/cliFlag.go:124 +0x104
github.com/urfave/cli/v2.(*Command).Run(0x104ff0c40, 0x1400018d680, {0x1400021d4a0, 0x3, 0x3})
	/tmp/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x71c
github.com/urfave/cli/v2.(*Command).Run(0x14000492160, 0x1400018d5c0, {0x14000126040, 0x4, 0x4})
	/tmp/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:272 +0x918
github.com/urfave/cli/v2.(*App).RunContext(0x14000160600, {0x104c506d0, 0x1050613e0}, {0x14000126040, 0x4, 0x4})
	/tmp/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x514
github.com/urfave/cli/v2.(*App).Run(...)
	/tmp/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:311
main.main()
	/private/tmp/grafanaExp/cmd/grafanaExp.go:38 +0x180
```
我看网上好多都是这个arm+go-sqlite3编译的问题：https://liujinye.gitbook.io/openshift-docs/raspberry-pi/macosgolang-bian-yi-arm-huan-jing-gosqlite3-xiang-mu 
目前mac arm用户可以自己拿源码go build 一份可以正常运行

**Comment by purpleroc** [comment]
然而，我换了个库啊。。。我拉个环境试试先

**Comment by purpleroc** [comment]
解决了，上次没换彻底。。。
https://github.com/A-D-Team/grafanaExp/commit/467dcf8e536bdac37784b326b001ac50b3363897

我发个新的 release

**Comment by purpleroc** [comment]
<img width="682" alt="image" src="https://github.com/user-attachments/assets/a47a0299-f641-4d0d-9a62-c14c0ebd63e5">
https://github.com/A-D-Team/grafanaExp/releases/tag/v1.4

**Comment by xia0le** [comment]
> <img alt="image" width="682" src="https://private-user-images.githubusercontent.com/8652319/348292719-a47a0299-f641-4d0d-9a62-c14c0ebd63e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3OTYyMzQsIm5iZiI6MTcyMDc5NTkzNCwicGF0aCI6Ii84NjUyMzE5LzM0ODI5MjcxOS1hNDdhMDI5OS1mNjQxLTRkMGQtOWE2Mi1jMTRjMGViZDYzZTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTJUMTQ1MjE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njk3NzhhYzFhYTRiNmZmOTM2ZmFkYzc1ZjM2ZWY4MTI0YzJiOTRhYzMxNzQyMDQ4MjdjZTZlY2NkMzFmMzE0ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XOvRvv24xbgRtKDWpqtOVXNHmQmklWfa-2TJaRSzsJI"> https://github.com/A-D-Team/grafanaExp/releases/tag/v1.4

好嘞师傅

**Comment by xia0le** [comment]
> <img alt="image" width="682" src="https://private-user-images.githubusercontent.com/8652319/348292719-a47a0299-f641-4d0d-9a62-c14c0ebd63e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3OTYyMzQsIm5iZiI6MTcyMDc5NTkzNCwicGF0aCI6Ii84NjUyMzE5LzM0ODI5MjcxOS1hNDdhMDI5OS1mNjQxLTRkMGQtOWE2Mi1jMTRjMGViZDYzZTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTJUMTQ1MjE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njk3NzhhYzFhYTRiNmZmOTM2ZmFkYzc1ZjM2ZWY4MTI0YzJiOTRhYzMxNzQyMDQ4MjdjZTZlY2NkMzFmMzE0ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XOvRvv24xbgRtKDWpqtOVXNHmQmklWfa-2TJaRSzsJI"> https://github.com/A-D-Team/grafanaExp/releases/tag/v1.4

好嘞师傅，没问题的
